---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
env:
  - PYENV_VERSION=3.6 PYTHON=python
before_install:
  - gem i bundler
before_script:
  - PYENV_VERSION=3.6 pip3 install --user matplotlib
